[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "genwatch"                
version = "0.1.0"
description = "Decorator for tracing Python generator internals"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name="Azema Shaik"}]
license = "Apache-2.0"
keywords = ["generator", "tracing", "decorator"]

[project.urls]
Homepage = "https://github.com/azema-shaik/genwatch"

[project.optional-dependencies]
test = ["pytest>=7.0",]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = ["tests"]
pythonpath = ["src"]